"""
capability_assessor.py — ROS2 node that drives the relay decision behaviour tree.

BUILDSPEC: §4.11
LAYER:     2 (sole publisher of outbound messages from the BT layer)
SUBSCRIBES: see subscription map below
PUBLISHES:
  /drone_NN/capability_report   — full BT state snapshot after every tick (§4.11)
  /drone_NN/pending_command     — FCU commands generated by BT action nodes (§4.11)
  /drone_NN/strategy_proposal   — relay strategy proposed by BT, to relay_strategy_evaluator (§4.11)
  /drone_NN/alert_intent        — safety alerts generated by FollowerSafetyExit (§4.11 item 11)
  /drone_NN/reauth_request      — reauthorization request to GC (G8 geometric/timer path, or reeval fast-path)

Hard rules this file must satisfy (BUILDSPEC §4.11, §5.5):
  - capability_report published every tick, unconditional  -> test_capability_report_every_tick
  - pending_command / pending_proposal / alert_intent drained and cleared each tick -> test_drains_and_clears_slots
  - No FSPL-inverse in this file; severity arrives via subscription  -> test_no_severity_computation
  - gc_leader_direct_quality subscribed only after F_tvalid passes   -> test_subscription_lifecycle_start
  - gc_leader_direct_quality unsubscribed on F_reject/F_decline      -> test_subscription_lifecycle_stop_washout
  - gc_leader_direct_quality unsubscribed on EXIT_RELAY              -> test_subscription_lifecycle_stop_exit
  - relay_assignment writes all four §6 blackboard keys              -> test_writes_radius_and_timer_keys

── Subscription map ──────────────────────────────────────────────────────────────────

Own drone topics (all JSON, written verbatim to blackboard):
  /drone_NN/signal_report      → bb["signal_report"]       per-hop SNR from signal_reader
  /drone_NN/drone_state        → bb["drone_state"]          FCU telemetry (battery, mode, pos, GPS)
  /drone_NN/link_state         → bb["link_state"]           gc_link_observer direct-link quality score
  /relay_tasking (shared)      → bb["relay_tasking_received"] GC tasking — sole BT entry trigger
  /drone_NN/current_role       → bb["current_role"]         plain string ("RELAYING", "IDLE", …)
  /drone_NN/movement_status    → bb["last_command_ack"]     four movement-phase guard signals,
                                  bb["distance_to_target_decreasing"]  unpacked into separate keys
                                  bb["offboard_mode_held"]             so each has its own timestamp
                                  bb["within_acceptance_radius"]
  /drone_NN/relay_assignment   → bb["current_relay_target"] GC authorization — writes four §6 keys
                                  bb["tolerance_radius_m"]
                                  bb["authorization_valid_until"]
                                  bb["reauth_requested_at"]  (reset to None, also resets _reauth_request_sent)
  /drone_NN/gc_link_quality    → bb["gc_leader_direct_quality"]  GC's view of direct link
                                  LIFECYCLE: subscribed on relay_assignment, unsubscribed on EXIT_RELAY
                                  or LET_LEADER_ISOLATE (§4.11 item 18)
  /drone_NN/reeval_trigger     → publishes reauth_request immediately (SNR fast-path from continuous_monitor)

Own radio health (F_radio — via subscription since v6.4, NOT in-process):
  /drone_NN/radio_health       → bb["follower_severity"]     own radio health from follower_radio_health_reader
                                  bb["follower_radio_range_m"]

Cross-drone radio health (DDS, two separate subscriptions):
  /{LEADER_ID}/radio_health    → bb["leader_severity"]       L_radio payload fields
                                  bb["leader_radio_range_m"]
  /gc/radio_health             → bb["gc_severity"]           G_radio payload fields
                                  bb["gc_radio_range_m"]
"""

import json   # parse every incoming ROS2 JSON message; encode the outgoing capability_report
import os     # read DRONE_ID and LEADER_ID from environment variables at startup
import sys    # prepend the package root to sys.path so demo_config can be imported by path
import time   # wall-clock time for tick duration measurement and capability_report timestamp

import rclpy                     # ROS2 Python client library — initialise, spin, shutdown
from rclpy.node import Node      # Node base class: create_publisher, create_subscription, create_timer
from rclpy.qos import QoSProfile, DurabilityPolicy, HistoryPolicy
from std_msgs.msg import String  # every topic in this system carries JSON in a ROS2 String message

# /current_role must match strategy_executor + relay_position_tracker publishers
# so late subscribers (e.g., this node after restart) receive the last role.
# QoS mismatch silently drops all messages. See strategy_executor.py.
CURRENT_ROLE_QOS = QoSProfile(
    depth=1,
    durability=DurabilityPolicy.TRANSIENT_LOCAL,
    history=HistoryPolicy.KEEP_LAST,
)

import py_trees  # behaviour-tree runtime — BehaviourTree wrapper, Status enum

# ── Identity ──────────────────────────────────────────────────────────────────

DRONE_ID = os.environ.get("DRONE_ID", "drone-01")
LEADER_ID = os.environ.get("LEADER_ID", "drone-01")


# ── Config loader ─────────────────────────────────────────────────────────────

def _load_config() -> dict:
    try:
        sys.path.insert(0, "/root/ros2_ws/src/drone_control/drone_control")
        from config.demo_config import DEMO_CONFIG
        return DEMO_CONFIG
    except Exception as e:
        raise RuntimeError(f"Cannot load demo_config: {e}")


# ── ROS2 topic name helper ────────────────────────────────────────────────────

def _ros_prefix(drone_id: str) -> str:
    return f"/{drone_id.replace('-', '_')}"


# ── BT status → capability string ────────────────────────────────────────────

def _status_to_string(root, data_freshness_node) -> str:
    status = root.status

    if status == py_trees.common.Status.SUCCESS:
        return "CAPABLE"

    if status == py_trees.common.Status.RUNNING:
        return "WAITING_DATA"

    if data_freshness_node and data_freshness_node.status == py_trees.common.Status.FAILURE:
        return "STALE_DATA"

    return "INCAPABLE"


# ── Pure blackboard helpers (testable without ROS2) ──────────────────────────

def _drain(bb, key: str, pub_fn) -> bool:
    """
    Drain one blackboard slot: read value, call pub_fn(value), then clear the key.
    Returns True if a value was present and published; False if the slot was empty.
    pub_fn receives the raw dict (not a ROS2 String) — callers wrap it as needed.
    BUILDSPEC §4.11: every output slot cleared after publish so next tick doesn't re-send.
    """
    value = bb.get(key)
    if value is None:
        return False
    bb.set(key, None)
    pub_fn(value)
    return True


def _apply_relay_assignment(bb, assignment: dict):
    """
    Write the four §6 blackboard keys from a relay_assignment payload.
    BUILDSPEC §6: all four keys must be written atomically on every assignment arrival.
    reauth_requested_at is reset to None so ReauthResponseTimedOut starts fresh for
    the new authorization period.
    """
    bb.set("current_relay_target",      assignment.get("r_target"))
    bb.set("tolerance_radius_m",        assignment.get("tolerance_radius_m"))
    bb.set("authorization_valid_until", assignment.get("valid_until"))
    bb.set("reauth_requested_at",       None)


# ── ROS2 Node ─────────────────────────────────────────────────────────────────

class CapabilityAssessor(Node):

    def __init__(self):
        node_name = f"capability_assessor_{DRONE_ID.replace('-', '_')}"
        super().__init__(node_name)

        self._config = _load_config()
        # Inject drone_id + leader_id into config so BT nodes (TaskingIsValid,
        # RelayActuallyImproved, etc.) can identify self/leader without duplicating
        # env lookups.  §2.4 relay_tasking doesn't carry leader_id; env-sourced fallback.
        self._config["drone_id"]  = DRONE_ID
        self._config["leader_id"] = LEADER_ID
        self._drone_id = DRONE_ID
        self._last_tick_duration_ms = 0.0
        # One-shot flag: True after reauth_request is published, reset on new relay_assignment.
        # Prevents spamming the GC every tick once G8 fires.
        self._reauth_request_sent = False

        from relay_bt.blackboard import TimestampedBlackboard
        from relay_bt.tree_builder import (
            build_relay_decision_tree, render_tree_ascii, walk_tree, dump_state
        )
        from relay_bt.condition_nodes import ConditionNodeBase, DataFreshness

        self._bb = TimestampedBlackboard()
        self._walk_tree = walk_tree
        self._dump_state = dump_state
        self._ConditionNodeBase = ConditionNodeBase

        self._tree_root = build_relay_decision_tree(self._bb, self._config)
        self._bt = py_trees.trees.BehaviourTree(root=self._tree_root)

        self._data_freshness_node = None
        for node in walk_tree(self._tree_root):
            if isinstance(node, DataFreshness):
                self._data_freshness_node = node
                break

        prefix = _ros_prefix(DRONE_ID)

        # ── Publishers ────────────────────────────────────────────────────────

        self._pub          = self.create_publisher(String, f"{prefix}/capability_report",  10)
        self._cmd_pub      = self.create_publisher(String, f"{prefix}/pending_command",     10)
        # BUILDSPEC §4.9: strategy_proposal is EXCLUSIVELY owned by
        # relay_strategy_evaluator.  It reads pending_proposal from capability_report,
        # applies content-hash dedup + snapping + enrichment per §2.5, then publishes.
        # A duplicate publisher here bypasses those invariants — do NOT re-add.
        # alert_intent drain — §4.11 item 11: FollowerSafetyExit writes to BB; we publish.
        # Layer 1 nodes must not publish directly (§5.5 Layer 1 discipline).
        self._alert_pub    = self.create_publisher(String, f"{prefix}/alert_intent",        10)
        # reauth_request: one-shot publish when G8 fires (reauth_requested_at written to BB).
        # Notifies relay_decision_authority to start a new authorization round.
        self._reauth_pub   = self.create_publisher(String, f"{prefix}/reauth_request",      10)

        # ── Subscriptions — own drone JSON topics ─────────────────────────────

        # BUILDSPEC §8: signal_report was removed from the design (no publisher).
        # Per-hop freshness now comes from radio_health via BandSensorNode.
        # follower_position was also removed (CHECK 1 dead-code cleanup 2026-08-24):
        # nothing published /{drone}/follower_position; nothing read bb["follower_position"];
        # BandSensorNode reads drone_state.position instead (condition_nodes.py:492).
        for topic, key in (
            ("drone_state",       "drone_state"),
            ("link_state",        "link_state"),
        ):
            self.create_subscription(
                String,
                f"{prefix}/{topic}",
                lambda m, k=key: self._on_msg(m, k),
                10,
            )

        self.get_logger().info(
            f"Subscribing to drone_state on {prefix}/drone_state"
        )

        self.create_subscription(
            String,
            f"{prefix}/current_role",
            lambda m: self._bb.set("current_role", m.data.strip()),
            CURRENT_ROLE_QOS,
        )

        self.create_subscription(
            String, f"{prefix}/movement_status", self._on_movement_status, 10
        )

        # BUILDSPEC §2.4: relay_tasking is a SHARED topic (not per-drone). Every
        # follower subscribes to the single /relay_tasking; GC broadcasts once.
        self.create_subscription(
            String,
            "/relay_tasking",
            lambda m: self._on_msg(m, "relay_tasking_received"),
            10,
        )

        # relay_assignment: GC's authorization reply — writes the four §6 BB keys and
        # starts the gc_leader_direct_quality lifecycle subscription (§4.11 item 18).
        self.create_subscription(
            String, f"{prefix}/relay_assignment", self._on_relay_assignment, 10
        )

        # reeval_trigger: continuous_monitor's SNR fast-path. Schema in §2.12;
        # subscription not in §4.11 Inputs list (DEVIATION vs. §4.11 only).
        # On receipt, publish reauth_request so SNR degradation during relay triggers a new GC round.
        # continuous_monitor's COOLDOWN_S debounces; GC's active-round guard deduplicates.
        self.create_subscription(
            String, f"{prefix}/reeval_trigger", self._on_reeval_trigger, 10
        )

        # Own radio health — F_radio via subscription (NOT in-process since v6.4).
        # follower_radio_health_reader.py publishes severity + range for the follower's
        # own hops; capability_assessor subscribes so BandSensorNode can read them.
        # DELIBERATELY ABSENT (BUILDSPEC §4.11): FSPL-inverse computation.
        # Severity arrives here, not derived here.
        leader_prefix = _ros_prefix(LEADER_ID)
        self.create_subscription(
            String, f"{prefix}/radio_health", self._on_follower_radio_health, 10
        )

        # ── Subscriptions — cross-drone radio health ──────────────────────────

        self.create_subscription(
            String, f"{leader_prefix}/radio_health", self._on_leader_radio_health, 10
        )

        # Leader live position — written to bb["leader_state"] so BandSensorNode and
        # the geometry gates use the real-time position of whichever drone is the leader.
        self.create_subscription(
            String,
            f"{leader_prefix}/drone_state",
            lambda m: self._on_leader_drone_state(m),
            10,
        )

        self.create_subscription(
            String, "/gc/radio_health", self._on_gc_radio_health, 10
        )

        # gc_link_quality subscription is LIFECYCLE-MANAGED (§4.11 item 18):
        # created in _ensure_quality_sub() when relay_assignment arrives (F_tvalid passed),
        # destroyed in _teardown_quality_sub() on EXIT_RELAY or LET_LEADER_ISOLATE.
        # DELIBERATELY ABSENT here: do not subscribe unconditionally.
        self._quality_sub = None

        # ── BT tick timer ─────────────────────────────────────────────────────

        tick_period = self._config.get("bt_tick_period_s", 0.5)
        self.create_timer(tick_period, self._tick)

        self.get_logger().info(
            f"capability_assessor started: drone={DRONE_ID} "
            f"tick={tick_period}s topic={prefix}/capability_report"
        )

        from relay_bt.tree_builder import render_tree_ascii
        self.get_logger().info(
            f"Tree:\n{render_tree_ascii(self._tree_root)}"
        )

    # ── Topic callbacks ───────────────────────────────────────────────────────

    def _on_msg(self, msg: String, key: str):
        try:
            data = json.loads(msg.data)
        except Exception as e:
            self.get_logger().warning(f"Bad JSON on {key}: {e}")
            return

        if key == "drone_state" and "drone_state" not in self._bb.timestamps:
            self.get_logger().info(f"drone_state first message received via ROS2")

        if key == "relay_tasking_received":
            self.get_logger().info(f"relay_tasking_received set: round_id={data.get('round_id')}")

        self._bb.set(key, data)

        # DELIBERATELY ABSENT (BUILDSPEC §4.11): FSPL-inverse / severity computation.
        # F_radio moved to follower_radio_health_reader.py (v6.4).
        # Follower severity arrives via /drone_NN/radio_health subscription, not here.

    def _on_follower_radio_health(self, msg: String):
        # Receives follower_radio_health_reader.py's §2.2 radio_health payload.
        # Two fields consumed: severity and range_m — these are the F_radio values
        # BandSensorNode reads from the blackboard as follower_severity and
        # follower_radio_range_m.  Separate keys (not the full payload) so each
        # gets its own freshness timestamp independently.
        try:
            s = json.loads(msg.data)
        except Exception as e:
            self.get_logger().warning(f"Bad JSON on follower radio_health: {e}")
            return

        if "severity" in s: self._bb.set("follower_severity",      s["severity"])
        if "range_m"  in s: self._bb.set("follower_radio_range_m", s["range_m"])
        hop = s.get("hop")
        if hop and "snr_db" in s:
            self._bb.set(f"follower_snr_db_{hop}", s["snr_db"])
        self._bb.set("follower_radio_health", s)

    def _on_movement_status(self, msg: String):
        try:
            s = json.loads(msg.data)
        except Exception as e:
            self.get_logger().warning(f"Bad JSON on movement_status: {e}")
            return

        self._bb.set("last_command_ack",              s.get("last_command_ack"))
        self._bb.set("distance_to_target_decreasing", s.get("distance_to_target_decreasing"))
        self._bb.set("offboard_mode_held",            s.get("offboard_mode_held"))
        self._bb.set("within_acceptance_radius",      s.get("within_acceptance_radius"))

    def _on_relay_assignment(self, msg: String):
        # GC authorization reply.  Writes the four §6 blackboard keys (BUILDSPEC §6)
        # and starts the gc_leader_direct_quality subscription (§4.11 item 18) so
        # Gate 6 (RelayStillNeeded) can monitor whether the direct link has recovered.
        try:
            a = json.loads(msg.data)
        except Exception as e:
            self.get_logger().warning(f"Bad JSON on relay_assignment: {e}")
            return

        _apply_relay_assignment(self._bb, a)
        # New authorization period — reset the one-shot flag so G8 can trigger another
        # reauth_request if this authorization period also expires or drifts.
        self._reauth_request_sent = False
        self._ensure_quality_sub()
        self.get_logger().info(
            f"relay_assignment received: target={a.get('r_target')} "
            f"valid_until={a.get('valid_until')}"
        )

    def _on_reeval_trigger(self, msg: String):
        try:
            data = json.loads(msg.data)
        except Exception:
            return
        reason = data.get("reason", "unknown")
        reauth_msg = String()
        reauth_msg.data = json.dumps({
            "drone_id":  self._drone_id,
            "timestamp": time.time(),
            "reason":    f"reeval:{reason}",
        })
        self._reauth_pub.publish(reauth_msg)
        self.get_logger().info(
            f"reeval_trigger(reason={reason!r}) → reauth_request published"
        )

    def _on_leader_radio_health(self, msg: String):
        try:
            s = json.loads(msg.data)
        except Exception as e:
            self.get_logger().warning(f"Bad JSON on leader radio_health: {e}")
            return

        self._bb.set("leader_radio_health", s)   # freshness sentinel for LeaderReachabilityFresh
        if "severity" in s: self._bb.set("leader_severity",      s["severity"])
        if "range_m"  in s: self._bb.set("leader_radio_range_m", s["range_m"])

    def _on_leader_drone_state(self, msg: String):
        try:
            s = json.loads(msg.data)
        except Exception as e:
            self.get_logger().warning(f"Bad JSON on leader drone_state: {e}")
            return
        self._bb.set("leader_state", s)

    def _on_gc_radio_health(self, msg: String):
        try:
            s = json.loads(msg.data)
        except Exception as e:
            self.get_logger().warning(f"Bad JSON on GC radio_health: {e}")
            return

        if "severity" in s: self._bb.set("gc_severity",      s["severity"])
        if "range_m"  in s: self._bb.set("gc_radio_range_m", s["range_m"])

    def _on_gc_link_quality(self, msg: String):
        try:
            s = json.loads(msg.data)
        except Exception as e:
            self.get_logger().warning(f"Bad JSON on gc_link_quality: {e}")
            return

        quality = s.get("quality")
        if quality is not None:
            self._bb.set("gc_leader_direct_quality", quality)

    # ── Subscription lifecycle ────────────────────────────────────────────────

    def _ensure_quality_sub(self):
        # Create the gc_leader_direct_quality subscription only if not already active.
        # Called from _on_relay_assignment() — the moment F_tvalid has passed and the
        # GC has authorized this drone.  Gate 6 (RelayStillNeeded) reads
        # gc_leader_direct_quality; subscribing here ensures data flows exactly when
        # the maintenance tree needs it.  BUILDSPEC §4.11 item 18.
        if self._quality_sub is None:
            prefix = _ros_prefix(self._drone_id)
            self._quality_sub = self.create_subscription(
                String, f"{prefix}/gc_link_quality", self._on_gc_link_quality, 10
            )

    def _teardown_quality_sub(self):
        # Destroy the gc_leader_direct_quality subscription when the drone exits or
        # declines relay (EXIT_RELAY or LET_LEADER_ISOLATE strategy detected in _tick).
        # Gate 6 is only relevant while RELAYING; unsubscribing avoids stale reads
        # from a previous relay episode carrying over into the next F_cap evaluation.
        if self._quality_sub is not None:
            self.destroy_subscription(self._quality_sub)
            self._quality_sub = None

    # ── BT tick ───────────────────────────────────────────────────────────────

    def _tick(self):
        t0 = time.time()
        self._bt.tick()
        self._last_tick_duration_ms = (time.time() - t0) * 1000.0
        if self._last_tick_duration_ms > 10.0:
            self.get_logger().warning(
                f"BT tick took {self._last_tick_duration_ms:.1f}ms (expected < 10ms)"
            )

        # If G8 just fired (RelayActuallyImproved wrote reauth_requested_at), notify the GC
        # exactly once per authorization period. Without this publish, the GC never starts a
        # reauth round and the drone exits unconditionally after ReauthResponseTimedOut (120s).
        if self._bb.get("reauth_requested_at") is not None and not self._reauth_request_sent:
            reauth_msg = String()
            reauth_msg.data = json.dumps({
                "drone_id":  self._drone_id,
                "timestamp": time.time(),
                "reason":    "authorization_expiring",
            })
            self._reauth_pub.publish(reauth_msg)
            self._reauth_request_sent = True
            self.get_logger().info(
                f"reauth_request published: drone={self._drone_id}"
            )

        # Build the report while pending_proposal is still on the blackboard —
        # _build_report() reads it to include in the capability_report payload.
        # All slot drains happen after this point.
        report = self._build_report()

        # Drain pending_command — RTL or other FCU commands generated by FollowerSafetyExit.
        # Published on a separate topic so the executor acts immediately without
        # waiting for the capability_report consumer to inspect the report.
        def _pub_cmd(cmd):
            msg = String()
            msg.data = json.dumps(cmd)
            self._cmd_pub.publish(msg)
            self.get_logger().warning(
                f"pending_command dispatched: {cmd.get('command')} "
                f"reason={cmd.get('reason')}"
            )
        _drain(self._bb, "pending_command", _pub_cmd)

        # Detect lifecycle-closing strategy BEFORE draining pending_proposal.
        # EXIT_RELAY means the drone is leaving relay role — gc_leader_direct_quality
        # is no longer needed.  LET_LEADER_ISOLATE means the drone declined and will
        # not enter relay — same teardown applies (washout path, §4.11).
        proposal = self._bb.get("pending_proposal")
        if proposal and proposal.get("strategy") in ("EXIT_RELAY", "LET_LEADER_ISOLATE"):
            self._teardown_quality_sub()

        # Clear pending_proposal from the blackboard after it's been included in
        # the capability_report above.  BUILDSPEC §4.9 assigns strategy_proposal
        # publishing EXCLUSIVELY to relay_strategy_evaluator, which subscribes to
        # /{prefix}/capability_report, applies content-hash dedup + snapping +
        # §2.5 enrichment, and publishes.  We MUST NOT publish it here — a second
        # publisher on that topic bypasses snapping and dedup.  Clearing the BB
        # (with a no-op pub_fn) keeps §4.11's "cleared after each tick" invariant.
        _drain(self._bb, "pending_proposal", lambda _p: None)

        # Drain alert_intent — §4.11 item 11.
        # FollowerSafetyExit writes alert_intent to the blackboard (Layer 1 discipline —
        # it cannot publish directly).  We drain and publish it here so G_task (the GC
        # task manager) receives the safety alert as a separate message, not buried inside
        # the capability_report.
        def _pub_alert(intent):
            # Enrich with drone_id at the publish boundary.  FollowerSafetyExit
            # (Layer 1) writes the payload but cannot know its own drone_id
            # (BB-only per §5.5).  Without this enrichment, RDA (G_task)
            # buckets every drone's alerts under "unknown" — correct-by-accident
            # for one follower, silently ambiguous for two or more.  Same class
            # as the leader_id multi-leader gap; fix here is close to free
            # since capability_assessor already carries drone_id in config.
            enriched = dict(intent)
            enriched.setdefault("drone_id", self._drone_id)
            msg = String()
            msg.data = json.dumps(enriched)
            self._alert_pub.publish(msg)
            self.get_logger().warning(
                f"alert_intent dispatched: drone={enriched['drone_id']} "
                f"type={intent.get('type')} reason={intent.get('reason')}"
            )
        _drain(self._bb, "alert_intent", _pub_alert)

        # Publish capability_report unconditionally — §4.11 hard rule.
        # HARD RULE (BUILDSPEC §4.11): published every tick regardless of BT outcome.
        # Consumers rely on this rate; skipping a tick would look like a node crash.
        msg = String()
        msg.data = json.dumps(report)
        self._pub.publish(msg)

        self.get_logger().info(
            f"tick status={report['status']} "
            f"capable={report['capable']} "
            f"dt={self._last_tick_duration_ms:.1f}ms"
        )

    # ── Report builder ────────────────────────────────────────────────────────

    def _build_report(self) -> dict:
        cfg     = self._config
        windows = cfg["staleness_windows_s"]
        now     = time.time()

        # Freshness section: drone_state only.
        # BUILDSPEC §8 removed signal_report; per-hop staleness lives in BandSensorNode.
        data_freshness = {}
        for key in ("drone_state",):
            max_age = windows[key]
            data    = self._bb.get(key)
            if data is None:
                data_freshness[key] = {"age_s": None, "fresh": False}
            else:
                ts = data.get("timestamp")
                if ts is None:
                    data_freshness[key] = {"age_s": None, "fresh": False}
                else:
                    age = round(now - ts, 3)
                    data_freshness[key] = {"age_s": age, "fresh": age <= max_age}

        checks = {}
        for node in self._walk_tree(self._tree_root):
            if isinstance(node, self._ConditionNodeBase):
                checks[node.name] = {
                    "pass":   node.status == py_trees.common.Status.SUCCESS,
                    "detail": getattr(node, "feedback_message", ""),
                }

        df_node    = self._data_freshness_node
        status_str = _status_to_string(self._tree_root, df_node)
        inputs     = self._collect_inputs()

        reason = ""
        if df_node and df_node.status == py_trees.common.Status.FAILURE:
            reason = df_node.feedback_message
        elif status_str == "CAPABLE":
            reason = "all checks passed"
        elif status_str == "INCAPABLE":
            for node in self._walk_tree(self._tree_root):
                if (isinstance(node, self._ConditionNodeBase)
                        and node.status == py_trees.common.Status.FAILURE):
                    reason = node.feedback_message
                    break

        pending_proposal = self._bb.get("pending_proposal")

        return {
            "drone_id":         self._drone_id,
            "timestamp":        time.time(),
            "capable":          status_str == "CAPABLE",
            "status":           status_str,
            "reason":           reason,
            "tick_duration_ms": round(self._last_tick_duration_ms, 2),
            "data_freshness":   data_freshness,
            "checks":           checks,
            "inputs":           inputs,
            "pending_proposal": pending_proposal,
        }

    def _collect_inputs(self) -> dict:
        # BUILDSPEC §8: signal_report removed. Read per-hop SNR from radio_health
        # via BB keys populated by _on_leader_radio_health / _on_follower_radio_health.
        ds = self._bb.get("drone_state")   or {}

        gc_snr      = self._bb.get("follower_snr_db_gc_to_follower")
        leader_snr  = self._bb.get("follower_snr_db_leader_to_follower")
        jamming_sev = 0.0   # jamming detection deferred; no source in current build

        pos        = ds.get("position") or {}
        gc_pos     = self._config["gc_pos"]
        dist_to_gc = None
        if pos:
            from relay_bt.geometry import haversine
            dist_to_gc = round(haversine(pos, gc_pos))

        # band_t_lo / band_t_hi written by BandSensorNode each tick; read here
        # so relay_strategy_evaluator can build capability_snapshot.t_lo/t_hi.
        # BUILDSPEC §2.5 — capability_snapshot requires t_lo and t_hi.
        return {
            "battery_pct":       ds.get("battery_pct"),
            "gps_fix_type":      ds.get("gps_fix_type"),
            "gc_snr_db":         gc_snr,
            "leader_snr_db":     leader_snr,
            "distance_to_gc":    dist_to_gc,
            "jamming_severity":  jamming_sev,
            "follower_severity": self._bb.get("follower_severity"),
            "band_t_lo":         self._bb.get("band_t_lo"),
            "band_t_hi":         self._bb.get("band_t_hi"),
        }


# ── Entry point ───────────────────────────────────────────────────────────────

def main():
    rclpy.init()
    node = CapabilityAssessor()

    try:
        rclpy.spin(node)
    except KeyboardInterrupt:
        pass

    finally:
        node.destroy_node()
        rclpy.shutdown()


if __name__ == "__main__":
    main()
